NSE_STOCKS = {
    "RELIANCE":   "Reliance Industries",
    "TCS":        "Tata Consultancy Services",
    "HDFCBANK":   "HDFC Bank",
    "INFY":       "Infosys",
    "ICICIBANK":  "ICICI Bank",
    "HINDUNILVR": "Hindustan Unilever",
    "SBIN":       "State Bank of India",
    "BHARTIARTL": "Bharti Airtel",
    "KOTAKBANK":  "Kotak Mahindra Bank",
    "LT":         "Larsen & Toubro",
    "AXISBANK":   "Axis Bank",
    "ASIANPAINT": "Asian Paints",
    "MARUTI":     "Maruti Suzuki",
    "SUNPHARMA":  "Sun Pharmaceutical",
    "TITAN":      "Titan Company",
    "WIPRO":      "Wipro",
    "ULTRACEMCO": "UltraTech Cement",
    "NTPC":       "NTPC",
    "POWERGRID":  "Power Grid Corporation",
    "BAJFINANCE": "Bajaj Finance",
    "BAJAJFINSV": "Bajaj Finserv",
    "HCLTECH":    "HCL Technologies",
    "NESTLEIND":  "Nestle India",
    "TECHM":      "Tech Mahindra",
    "INDUSINDBK": "IndusInd Bank",
    "ADANIENT":   "Adani Enterprises",
    "ADANIPORTS": "Adani Ports",
    "COALINDIA":  "Coal India",
    "JSWSTEEL":   "JSW Steel",
    "TATAMOTORS": "Tata Motors",
    "TATASTEEL":  "Tata Steel",
    "ONGC":       "Oil & Natural Gas Corporation",
    "ITC":        "ITC",
    "CIPLA":      "Cipla",
    "DRREDDY":    "Dr. Reddy's Laboratories",
    "DIVISLAB":   "Divi's Laboratories",
    "EICHERMOT":  "Eicher Motors",
    "HEROMOTOCO": "Hero MotoCorp",
    "BPCL":       "Bharat Petroleum",
    "IOC":        "Indian Oil Corporation",
    "GRASIM":     "Grasim Industries",
    "HINDALCO":   "Hindalco Industries",
    "VEDL":       "Vedanta",
    "TATACONSUM": "Tata Consumer Products",
    "BRITANNIA":  "Britannia Industries",
    "APOLLOHOSP": "Apollo Hospitals",
    "BAJAJ-AUTO": "Bajaj Auto",
    "SHREECEM":   "Shree Cement",
    "UPL":        "UPL",
    "SBILIFE":    "SBI Life Insurance",
    "HDFCLIFE":   "HDFC Life Insurance",
    "ICICIPRULI": "ICICI Prudential Life",
    "ICICIGI":    "ICICI Lombard General Insurance",
    "MUTHOOTFIN": "Muthoot Finance",
    "PNB":        "Punjab National Bank",
    "BANKBARODA": "Bank of Baroda",
    "CANBK":      "Canara Bank",
    "FEDERALBNK": "Federal Bank",
    "IDFCFIRSTB": "IDFC First Bank",
    "BANDHANBNK": "Bandhan Bank",
    "RBLBANK":    "RBL Bank",
    "AUBANK":     "AU Small Finance Bank",
    "CHOLAFIN":   "Cholamandalam Investment",
    "M&M":        "Mahindra & Mahindra",
    "ASHOKLEY":   "Ashok Leyland",
    "BALKRISIND": "Balkrishna Industries",
    "MOTHERSON":  "Samvardhana Motherson",
    "HAVELLS":    "Havells India",
    "VOLTAS":     "Voltas",
    "CROMPTON":   "Crompton Greaves Consumer",
    "ZOMATO":     "Zomato",
    "PAYTM":      "One97 Communications (Paytm)",
    "NYKAA":      "FSN E-Commerce (Nykaa)",
    "POLICYBZR":  "PB Fintech (PolicyBazaar)",
    "DELHIVERY":  "Delhivery",
    "IRCTC":      "Indian Railway Catering",
    "HAL":        "Hindustan Aeronautics",
    "BEL":        "Bharat Electronics",
    "BHEL":       "Bharat Heavy Electricals",
    "NMDC":       "NMDC",
    "SAIL":       "Steel Authority of India",
    "RECLTD":     "REC Limited",
    "PFC":        "Power Finance Corporation",
    "IRFC":       "Indian Railway Finance Corp",
    "GAIL":       "GAIL India",
    "IGL":        "Indraprastha Gas",
    "MGL":        "Mahanagar Gas",
    "PETRONET":   "Petronet LNG",
    "HINDPETRO":  "Hindustan Petroleum",
    "AUROPHARMA": "Aurobindo Pharma",
    "BIOCON":     "Biocon",
    "LUPIN":      "Lupin",
    "TORNTPHARM": "Torrent Pharmaceuticals",
    "ALKEM":      "Alkem Laboratories",
    "IPCALAB":    "Ipca Laboratories",
    "ABBOTINDIA": "Abbott India",
    "GLAXO":      "GlaxoSmithKline Pharma",
    "PFIZER":     "Pfizer",
    "DELTACORP":  "Delta Corp",
    "ZEEL":       "Zee Entertainment",
    "SUNTV":      "Sun TV Network",
    "PVRINOX":    "PVR Inox",
    "INOXWIND":   "Inox Wind",
    "TATAPOWER":  "Tata Power",
    "ADANIGREEN": "Adani Green Energy",
    "SUZLON":     "Suzlon Energy",
    "CESC":       "CESC",
    "TORNTPOWER": "Torrent Power",
    "OBEROIRLTY": "Oberoi Realty",
    "DLF":        "DLF",
    "GODREJPROP": "Godrej Properties",
    "PHOENIXLTD": "Phoenix Mills",
    "MINDTREE":   "LTIMindtree",
    "LTIM":       "LTIMindtree",
    "MPHASIS":    "Mphasis",
    "COFORGE":    "Coforge",
    "PERSISTENT": "Persistent Systems",
    "OFSS":       "Oracle Financial Services",
    "KPITTECH":   "KPIT Technologies",
    "TATAELXSI":  "Tata Elxsi",
    "DIXON":      "Dixon Technologies",
    "AMBER":      "Amber Enterprises",
    "VGUARD":     "V-Guard Industries",
    "POLYCAB":    "Polycab India",
    "KEI":        "KEI Industries",
}

INDICES = {
    "NIFTY":      "Nifty 50",
    "BANKNIFTY":  "Nifty Bank",
    "FINNIFTY":   "Nifty Financial Services",
    "MIDCPNIFTY": "Nifty Midcap Select",
}

# yfinance symbols for indices (for spot price only)
INDEX_YF_SYMBOLS = {
    "NIFTY":      "^NSEI",
    "BANKNIFTY":  "^NSEBANK",
    "FINNIFTY":   "NIFTY_FIN_SERVICE.NS",
    "MIDCPNIFTY": "^NSEMDCP50",
}

def search_stocks(query):
    query = query.upper().strip()
    if not query:
        return []
    results = []
    for symbol, name in NSE_STOCKS.items():
        if query in symbol or query in name.upper():
            results.append((symbol, name))
    return sorted(results, key=lambda x: (not x[0].startswith(query), x[0]))[:10]
